### ISSUE TITLE
Detail dataset

### ISSUE THREAD

**Issue by juandavidgutier** [gasparrini/2019_sera_StatMed_Rcode#1]
Hi @gasparrini 
I am trying to understand the script 04.DoseResponseMA.R. I see that the script uses eight cohort studies participating in the Pooling Project of Prospective Studies of Diet and Cancer, included in the dataframe named 'alcohol'. The dataframe 'alcohol' has 48 observations of 7 variables. My question is about the variable 'peryears'. What does it mean, and how was it calculated?

Best regards,

Juan

**Comment by gasparrini** [comment]
Hi Juan,

thanks for your interest.
The data used in the example are from the alcohol dataset from the mixmeta package. You can have a look at its help page typing help(alcohol), and find out that the variable peryears represents the amount of person-time for each dose category.

Best
-Antonio Gasparrini
